### PR TITLE
added while loop handler

### PR DESCRIPTION
**Pull request by CandiceMeow**
Added while loop handler and cleaned up the formatting or the code

### CODE REVIEW

**Review by orenjina — COMMENTED** [review]
- Fix the test case issue: re-write tests or re-write code to fit the outcome of the test
- Add some more comments on what "traverse" is; I don't quite get what you meant by that
- Rather than only putting the corner case, put what is expected to be returned in regular cases too. Javadocs will also structure this a lot better for multiple reasons.
- I like how each operator case is split and documented inside, but add some more method comments to make their functions more documented too.

**Comment by CandiceMeow** [comment]
@Jedido can you check out the test and maybe modify it a bit? I realized my original if implementation was incorrect since it should have added a false branch directly pointing to the statement after the if when there is no else case.

**Comment by Jedido** [comment]
> @Jedido can you check out the test and maybe modify it a bit? I realized my original if implementation was incorrect since it should have added a false branch directly pointing to the statement after the if when there is no else case.

Got it, updated the tests to match our current implementation

**Comment by CandiceMeow** [comment]
will add more comments and java doc but since the code looks good I will merge first so that @AndrewLiuRM @xiaoyg2 can start intergrating

**Pull request merged**
